title: "Admire Tarisirayi Chirume | Senior Economist & Policy Researcher"
description: "Official professional and academic profile of Admire Tarisirayi Chirume, Senior Economist at the Reserve Bank of Zimbabwe. Specializing in macro-fiscal modeling, DSGE, policy research, and data analytics."
author: "Admire T. Chirume"
theme: minima
markdown: kramdown

baseurl: "/Chirume-Admire-T"
url: "https://atchirume.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - profile.md
  - education.md
  - work.md
  - skills.md
  - achievements.md
  - publications.md
  - hobbies.md
  - references.md
  - projects.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
