title: "Admire Tarisirayi. Chirume | Senior Economist & Policy Researcher"
description: "Official professional and academic profile of Admire Tarisirayi Chirume, Senior Economist at the Reserve Bank of Zimbabwe. Specializing in macro-fiscal modeling, DSGE, policy research, and data analytics."
author: "Admire T. Chirume"
theme: minima
markdown: kramdown

baseurl: "" # the subpath of your site, e.g. /Chirume-Admire-T
url: "https://atchirume.github.io" # your GitHub Pages URL

# SEO plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation menu
navigation:
  - title: "Profile"
    url: /profile/
  - title: "Education"
    url: /education/
  - title: "Work Experience"
    url: /work/
  - title: "Skills"
    url: /skills/
  - title: "Achievements"
    url: /achievements/
  - title: "Publications"
    url: /publications/
  - title: "Hobbies"
    url: /hobbies/
  - title: "References"
    url: /references/
  - title: "Projects"
    url: /projects/


# Build settings (GitHub Pages)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
