title: "Chirume Admire Tarisirayi | CV"
description: "Official Curriculum Vitae"
theme: minima
markdown: kramdown

# Optional but useful
baseurl: "" # the subpath of your site, e.g. /Chirume-Admire-T
url: "https://atchirume.github.io" # the base hostname & protocol

# Navigation menu (for custom layouts)
navigation:
  - title: "Profile"
    url: /profile/
  - title: "Education"
    url: /education/
  - title: "Work Experience"
    url: /work/
  - title: "Skills"
    url: /skills/
  - title: "Achievements"
    url: /achievements/
  - title: "Publications"
    url: /publications/
  - title: "Hobbies"
    url: /hobbies/
  - title: "References"
    url: /references/
